# Homebrew formula for the makima CLI.
#
# Generated by sh/update-formula.sh - do not hand-edit the checksums.
#
#   brew tap soryu-co/makima
#   brew install makima
#
# The tap lives at github.com/soryu-co/homebrew-makima. The name matters:
# `brew tap owner/name` resolves to `github.com/owner/homebrew-name`, so a tap
# repo without the `homebrew-` prefix can only be tapped by passing its URL
# explicitly - which nobody does, and which made every documented install fail.
#
# Installs the prebuilt release archive rather than building from source: the
# workspace is ~650 crates, and a from-source formula would put a multi-minute
# compile in front of every `brew install`.
class Makima < Formula
  desc "Self-hosted daemon orchestration and terminal coding harness"
  homepage "https://github.com/soryu-co/makima"
  version "0.11.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soryu-co/makima/releases/download/v0.11.0/makima-v0.11.0-macos-arm64.tar.gz"
      sha256 "8b5dc244fcf72d76694a4bcab7b7f6a654614f005edba20a0479c35b756430ee"
    end
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.11.0/makima-v0.11.0-macos-x86_64.tar.gz"
      sha256 "2f36a18e43368b98cc85dff6933c0f2d08dbe960ade2f1287406d6a8e553ce56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.11.0/makima-v0.11.0-linux-x86_64.tar.gz"
      sha256 "c932435b3241281cedcd9cfbf45405f14a4333eecb6d6cf99ff0146e608a1947"
    end
  end

  def install
    # Each archive contains a single `makima` binary at its root.
    bin.install "makima"
  end

  test do
    # The usual failure for a downloaded-binary formula is an architecture
    # mismatch, which shows up immediately as a failure to exec.
    assert_match "makima", shell_output("#{bin}/makima --help 2>&1", 0)
  end
end
