# Homebrew formula for the makima CLI.
#
# Generated by sh/update-formula.sh - do not hand-edit the checksums.
#
#   brew tap soryu-co/makima
#   brew install makima
#
# The tap lives at github.com/soryu-co/homebrew-makima. The name matters:
# `brew tap owner/name` resolves to `github.com/owner/homebrew-name`, so a tap
# repo without the `homebrew-` prefix can only be tapped by passing its URL
# explicitly - which nobody does, and which made every documented install fail.
#
# Installs the prebuilt release archive rather than building from source: the
# workspace is ~650 crates, and a from-source formula would put a multi-minute
# compile in front of every `brew install`.
class Makima < Formula
  desc "Self-hosted daemon orchestration and terminal coding harness"
  homepage "https://github.com/soryu-co/makima"
  version "0.12.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soryu-co/makima/releases/download/v0.12.0/makima-v0.12.0-macos-arm64.tar.gz"
      sha256 "28ca75cceebca8d21025bca8f70e31ad644968088b215a8af45befc56d20f4a0"
    end
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.12.0/makima-v0.12.0-macos-x86_64.tar.gz"
      sha256 "dc175046bee43daad257a972e41b28ed542c66b9aa48f7ab10faa1c492f0aaf2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.12.0/makima-v0.12.0-linux-x86_64.tar.gz"
      sha256 "d522e89e9f5fed2d55b8c00df7b2a7026d2bc90ee074e126104c8691f380f1e3"
    end
  end

  def install
    # Each archive contains a single `makima` binary at its root.
    bin.install "makima"
  end

  test do
    # The usual failure for a downloaded-binary formula is an architecture
    # mismatch, which shows up immediately as a failure to exec.
    assert_match "makima", shell_output("#{bin}/makima --help 2>&1", 0)
  end
end
