# Homebrew formula for the makima CLI.
#
# Generated by sh/update-formula.sh - do not hand-edit the checksums.
#
#   brew tap soryu-co/makima
#   brew install makima
#
# The tap lives at github.com/soryu-co/homebrew-makima. The name matters:
# `brew tap owner/name` resolves to `github.com/owner/homebrew-name`, so a tap
# repo without the `homebrew-` prefix can only be tapped by passing its URL
# explicitly - which nobody does, and which made every documented install fail.
#
# Installs the prebuilt release archive rather than building from source: the
# workspace is ~650 crates, and a from-source formula would put a multi-minute
# compile in front of every `brew install`.
class Makima < Formula
  desc "Self-hosted daemon orchestration and terminal coding harness"
  homepage "https://github.com/soryu-co/makima"
  version "0.8.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/soryu-co/makima/releases/download/v0.8.1/makima-v0.8.1-macos-arm64.tar.gz"
      sha256 "85bbc2c1a1201257ef4a86f3584fabf5a7e1121b15be537860f1421c920c9b7b"
    end
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.8.1/makima-v0.8.1-macos-x86_64.tar.gz"
      sha256 "f8fcebdd86c527eb60d9896f6c1763eca5f4bf7d50844efae4f4726d7c47d82d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/soryu-co/makima/releases/download/v0.8.1/makima-v0.8.1-linux-x86_64.tar.gz"
      sha256 "072d3d47169e78ec2aee79bb91785c2d34842d24c029abb758a8481d767056eb"
    end
  end

  def install
    # Each archive contains a single `makima` binary at its root.
    bin.install "makima"
  end

  test do
    # The usual failure for a downloaded-binary formula is an architecture
    # mismatch, which shows up immediately as a failure to exec.
    assert_match "makima", shell_output("#{bin}/makima --help 2>&1", 0)
  end
end
